puts "The students of Villians Acamdemy"
puts "------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked With of the West"
puts "Terminator"
puts "Freddy Kreuger"
puts "The Joker"
puts "Joffery Baratheon"
puts "Norman Bates"
print "Overall, we have "
print 11
puts " great students."